export const browserCoreExamples = [
  "qingclaws browser status",
  "qingclaws browser start",
  "qingclaws browser stop",
  "qingclaws browser tabs",
  "qingclaws browser open https://example.com",
  "qingclaws browser focus abcd1234",
  "qingclaws browser close abcd1234",
  "qingclaws browser screenshot",
  "qingclaws browser screenshot --full-page",
  "qingclaws browser screenshot --ref 12",
  "qingclaws browser snapshot",
  "qingclaws browser snapshot --format aria --limit 200",
  "qingclaws browser snapshot --efficient",
  "qingclaws browser snapshot --labels",
];

export const browserActionExamples = [
  "qingclaws browser navigate https://example.com",
  "qingclaws browser resize 1280 720",
  "qingclaws browser click 12 --double",
  'qingclaws browser type 23 "hello" --submit',
  "qingclaws browser press Enter",
  "qingclaws browser hover 44",
  "qingclaws browser drag 10 11",
  "qingclaws browser select 9 OptionA OptionB",
  "qingclaws browser upload /tmp/qingclaws/uploads/file.pdf",
  'qingclaws browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "qingclaws browser dialog --accept",
  'qingclaws browser wait --text "Done"',
  "qingclaws browser evaluate --fn '(el) => el.textContent' --ref 7",
  "qingclaws browser console --level error",
  "qingclaws browser pdf",
];
